name: Team Member Request
description: Form to request a new team member within the organization
title: "[Team Member Request]: [New Member Name]"
assignees:
  - Admin_14_1  

body:
  - type: markdown
    attributes:
      value: |
        **This form is for requesting a new team member to be added to the organization.**
        Please fill in the details below. Please only request addition for yourself. 

  - type: input
    id: new_member_name
    attributes:
      label: New Member Name
      description: Provide your full name.
      placeholder: "Enter the name"

  - type: dropdown
    id: access_level
    attributes:
      label: Access Level
      description: What level of access should the new team member have?
      options:
        - "Read"
        - "Write"
        - "Admin"
        - "Custom (specify below)"

  - type: markdown
    attributes:
      value: "**Requester Information** (Auto-filled)"

  - type: input
    id: requester
    attributes:
      label: Requester GitHub Username
      description: This field is auto-filled with the GitHub username of the requester.
      value: "@{{ github.actor }}"
      readonly: true

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other details or comments about this request?
      placeholder: "Enter additional notes if any"
